[general]
shuffle_caption = false
caption_extension = ".txt"
keep_tokens = 1

[[datasets]]
resolution = 512
batch_size = 1
enable_bucket = true
min_bucket_reso = 384
max_bucket_reso = 768

  [[datasets.subsets]]
  image_dir = "/Users/yoon/Projects/arazzi-archive/training/image/3_arazzi"
  num_repeats = 3
